### ISSUE TITLE
Error running snakemake workflow (MissingRuleException)

### ISSUE THREAD

**Issue by anikaliu** [satijalab/azimuth-meta-analysis#1]
Hello,
first of all, thanks for providing this repo! I'm just getting started working on some of the lung datasets that have been processed by you, so this is a very useful resource to get started in this new field.

I've cloned the repo and tried to run the snakemake workflow as described in the readme, however, I ran into the following issue: 

`snakemake --use-singularity --cores 2 RULE`
`Building DAG of jobs...`
`MissingRuleException:`
`No rule to produce RULE (if you use input functions make sure that they don't raise unexpected exceptions).`

Would you be able to help me with this?

Best wishes,
Anika

**Comment by andrewwbutler** [comment]
Hi Anika,

You need to replace `RULE` with the name of the snakemake rule that you want to run. For example, if you wanted to produce a Seurat object with all the merged results

```bash
snakemake --use-singularity --cores 2 merge_all
```

**Comment by anikaliu** [comment]
Hi Andrew, 
that makes so much sense, thanks for your reply!
