### ISSUE TITLE
snakmake file error

### ISSUE THREAD

**Issue by m0nib** [satijalab/azimuth-meta-analysis#2]
Hi,

when running snakemake --use-singularity download
Building DAG of jobs...
WorkflowError:
Target rules may not contain wildcards. Please specify concrete files or a rule without wildcards at the command line, or have a rule without wildcards at the very top of your workflow (e.g. the typical "rule all" which just collects all results you want to generate in the end).

how can this be fixed.

Thank you

best regards
Monib

**Comment by andrewwbutler** [comment]
Hi Monib,

You won't be able to run individual rules where Snakemake can't resolve the wildcards. Without defining new rules yourself, you can either run `merge_all` or `export_cellxgene` depending on what you want to produce.
